logging:
  file: log/blog-prod.log
  level:
    com:
      sheng: info
    root: warn
server:
  port: 8050
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: njgvu83668456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true